version: '2'
services:
 web:
  build: ./web
  image: reloca/eve
  env_file: .env
  ports:
    - "5000:5000"
    - "80:80"
  volumes:
    - ./web/app:/app
  command: python -u /app/app.py
  links:
    - db
  hostname: "app01"
  depends_on:
    - db

 db:
  build: ./db
  image: reloca/mongodb
  ports: 
    - "27017:27017"
  hostname: "db01"
